Added Windows 10 Development post
curiositymotive/curiositymotive.github.io pull request #40
Opened 2017-02-16 17:33 UTC by ryanbillingsley

2017-02-17 15:56 UTC, nsbingham requested changes
@ryanbillingsley overall looks great! 

It does look like you're missing an image for the development category, but I think your post images could be repurposed for that. Nice images!

2017-02-17 15:56 UTC, nsbingham commented on _posts/2017-02-16-You-Want-The-Impossible.md
> +There were also some nice-to-haves I wanted as well. I use a 256 color theme for VIM and I have grown quite attached to it, so I wanted [256 xterm color](https://commons.wikimedia.org/wiki/File:Xterm
@ryanbillingsley airline is capitalized differently in two spots

2017-02-17 15:56 UTC, nsbingham commented on _posts/2017-02-16-You-Want-The-Impossible.md
> +I knew there were a lot of avenues I could pursue with none of them being necessarily the “right” one. I limited my selection down to just a few so I could manage my findings. I started with [Bash on
@ryanbillingsley you probably want to do a find and replace for fancy quotes with escaped characters. same for apostrophes

2017-02-20 19:53 UTC, ryanbillingsley commented
@nsbingham I fixed the changes you mentioned if you could give a once over, I would appreciate it

2017-02-20 20:28 UTC, nsbingham commented
@ryanbillingsley the quotes and spelling look good. you're still missing a category image for the "development" category

2017-02-20 21:12 UTC, ryanbillingsley commented
@nsbingham changed the category to `hacking`

2017-02-20 21:16 UTC, nsbingham commented
@ryanbillingsley looks good!

2017-02-20 21:48 UTC, merged